version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: tracking_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_kamu
      MYSQL_DATABASE: db_tracking
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: